v7.0, SLE15: linux/gfp.h: avoid __VA_OPT__ in default_gfp
SLE15 builds fail because its compiler does not support the __VA_OPT__
use in the default_gfp() compatibility macro:
  compat-include/linux/gfp.h:11:52: error: implicit declaration of
  function '__VA_OPT__'; did you mean '__CHAR_BIT__'?

Backport upstream commit 551d44200152 ("default_gfp(): avoid using the
"newfangled" __VA_OPT__ trick") and use the traditional gcc
',##__VA_ARGS__' form instead.

Signed-off-by: Ralf Lici <ralf@mandelbit.com>