linux/gfp.h: backport 551d44200152
On SLE15 builds fail with:
  compat-include/linux/gfp.h:11:52: error: implicit declaration of
  function '__VA_OPT__'; did you mean '__CHAR_BIT__'?

This is caused by the use of __VA_OPT__ in the default_gfp definition.

Backport upstream commit 551d44200152cb26f75d2ef990aeb6185b7e37fd
("default_gfp(): avoid using the "newfangled" __VA_OPT__ trick") which
removes __VA_OPT__ and uses the traditional gcc ',##__VA_ARGS__' syntax.

Signed-off-by: Ralf Lici <ralf@mandelbit.com>